-- Asset Management System Database Initialization Script
-- Database: asset_db

CREATE DATABASE IF NOT EXISTS asset_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE asset_db;

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL DEFAULT 'User',
    role VARCHAR(50) NOT NULL,
    department VARCHAR(100),
    status VARCHAR(50) DEFAULT 'APPROVED',
    reset_token VARCHAR(255),
    reset_token_expiry TIMESTAMP NULL
);

-- 2. Category Table
CREATE TABLE IF NOT EXISTS category (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    use_ocr BOOLEAN DEFAULT FALSE
);

-- 3. Department Table
CREATE TABLE IF NOT EXISTS department (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- 4. Asset Table
CREATE TABLE IF NOT EXISTS asset (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    serial_number VARCHAR(100) UNIQUE NOT NULL,
    status VARCHAR(50) NOT NULL,
    location VARCHAR(255),
    image_url VARCHAR(500),
    use_yn CHAR(1) DEFAULT 'Y',
    FOREIGN KEY (category_id) REFERENCES category(id)
);

-- 5. Transaction Table
CREATE TABLE IF NOT EXISTS `transaction` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    asset_id INT,
    user_id INT NOT NULL,
    type VARCHAR(50) NOT NULL,
    transaction_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_date DATE NULL,
    note TEXT,
    signature_data LONGTEXT,
    ocr_data TEXT,
    FOREIGN KEY (asset_id) REFERENCES asset(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 6. Rental Request Table
CREATE TABLE IF NOT EXISTS rental_request (
    id INT AUTO_INCREMENT PRIMARY KEY,
    asset_id INT NOT NULL,
    user_id INT NOT NULL,
    request_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    planned_due_date DATE NOT NULL,
    purpose TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    processed_by INT,
    process_date TIMESTAMP NULL,
    reject_reason TEXT,
    ocr_data TEXT,
    FOREIGN KEY (asset_id) REFERENCES asset(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (processed_by) REFERENCES users(id)
);

-- 7. Notice Table
CREATE TABLE IF NOT EXISTS notice (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    author_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL,
    FOREIGN KEY (author_id) REFERENCES users(id)
);

-- 8. Repair Log Table
CREATE TABLE IF NOT EXISTS repair_log (
    id INT AUTO_INCREMENT PRIMARY KEY,
    asset_id INT NOT NULL,
    reported_by INT NOT NULL,
    reason TEXT NOT NULL,
    estimated_cost DECIMAL(10,2),
    final_cost DECIMAL(10,2),
    status VARCHAR(50) NOT NULL DEFAULT 'IN_PROGRESS',
    start_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_date TIMESTAMP NULL,
    FOREIGN KEY (asset_id) REFERENCES asset(id),
    FOREIGN KEY (reported_by) REFERENCES users(id)
);

-- 9. Chat Message Table
CREATE TABLE IF NOT EXISTS chat_message (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sender_id INT NOT NULL,
    receiver_id INT,
    content TEXT NOT NULL,
    timestamp DATETIME NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE
);

-- 10. Board Post Table
CREATE TABLE IF NOT EXISTS board_post (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    author_id INT NOT NULL,
    view_count INT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL,
    FOREIGN KEY (author_id) REFERENCES users(id)
);

-- 11. Board Comment Table
CREATE TABLE IF NOT EXISTS board_comment (
    id INT AUTO_INCREMENT PRIMARY KEY,
    post_id INT NOT NULL,
    author_id INT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL,
    FOREIGN KEY (post_id) REFERENCES board_post(id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES users(id)
);

-- Initial Data
-- Default Departments
INSERT IGNORE INTO department (id, name) VALUES (1, 'Engineering');
INSERT IGNORE INTO department (id, name) VALUES (2, 'Human Resources');
INSERT IGNORE INTO department (id, name) VALUES (3, 'Information Technology');
INSERT IGNORE INTO department (id, name) VALUES (4, 'Marketing');
INSERT IGNORE INTO department (id, name) VALUES (5, 'Sales');

-- Default Admin User (Password: admin123)
-- Hash generated by BCrypt
INSERT IGNORE INTO users (email, password, name, role, department, status) 
VALUES ('admin@asset.com', '$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00DMxs.TVuHOn2', 'Admin User', 'ADMIN', 'IT', 'APPROVED');

-- System Admin User for Notifications (Password: sysadmin123)
INSERT IGNORE INTO users (email, password, name, role, department, status) 
VALUES ('assetSysAdmin@asset.com', '$2a$10$fVfM5N7K.9t9Nq9yR9.G1.v6u9Y8k.T9sY9V9e9v9V9v9V9V9V9V9', '시스템 알림', 'ADMIN', 'SYSTEM', 'APPROVED');

-- Sample Categories
INSERT IGNORE INTO category (id, name, use_ocr) VALUES (1, 'Electronics', TRUE);
INSERT IGNORE INTO category (id, name, use_ocr) VALUES (2, 'Furniture', FALSE);
INSERT IGNORE INTO category (id, name, use_ocr) VALUES (3, 'Software License', FALSE);
INSERT IGNORE INTO category (id, name, use_ocr) VALUES (4, 'Others', FALSE);
