server:
  port: 8080

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:mysql://localhost:3306/asset_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always # DB schema will be initialized and IF NOT EXISTS will prevent loss
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3-vl:8b
  mail:
    host: smtp.gmail.com
    port: 587
    username: waitanboy@gmail.com
    password: msdwrnjtggfmoyqt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000 # 24 hours in ms
    cookie-name: jwt_token

logging:
  level:
    org.springframework.security: DEBUG

